version: 3

server: https://app.fossa.com
apiKey: 3a3c184d4cf24b14c923028df7956ce7

project:
  id: gitlab.com/sivasaiganesh/java-app-r
  name: Java-App
  team: cli-team
  policy: custom-cli-policy
  link: fossa.com
  url: gitlab.com/sivasaiganesh/java-app-r
  
  releaseGroup:
    name: release-group-name
    release: 123-release-candidate
  labels:
    - project-label-1
    - test-project

revision:
  
  branch: main

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    only:
      - "**/*.rb"
    exclude:
      - ".git/**"
      - "test/**/*.rb"

targets:
  only:
    - type: maven
      path: src/main/
  exclude:
    - type: bundler

paths:
  only:
    - ./vendor/django
    - ./test
  exclude:
    - ./vendor/django/test

telemetry:
  scope: full
