version: 3
server: https://app.fossa.com
apiKey: 3a3c184d4cf24b14c923028df7956ce7

project:
  id: https://gitlab.com/sivasaiganesh/java-app-r
  name: java-app-r
  team: cli-team
  policy: custom-cli-policy
  link: fossa.com

revision:
  
  branch: master
targets:
  only:
    - type: maven
      path: java-app-r/src/main/java
  exclude:
    - type: bundler
