version: 3
project_type: maven

language: java
package_manager: maven
revision:
  #commit: "12345"
  branch: main
# Specify the location of your source code and package file.
# If not specified, Fossa will try to infer them.
source_root: src/main/java
package_file: pom.xml

project:
  
  #name: Java-Application
  #team: analytic-team
  labels:
    - project-label-1
    - test-project
  url: gitlab.com/sivasaiganesh/java-app-r
  id: gitlab.com/sivasaiganesh/java-app-r
  name: "java-app-r"
analysis:
  exclude:
    - "/builds/sivasaiganesh/java-app-r/src/test/"
    - "**/*.txt"
