version: 3
project_type: maven

analysis:
  exclude:
    - "java-app-r/excluded_dir/"
    - "**/*.txt"

project:
  language: java
  packageManager: maven
  sourceRoot: src/main/java
  packageFile: pom.xml
