version: 1
project_type: maven

language: java
package_manager: maven

# Specify the location of your source code and package file.
# If not specified, Fossa will try to infer them.
source_root: src/main/java
package_file: pom.xml

analysis:
  exclude:
    - "/builds/sivasaiganesh/java-app-r/src/test/"
    - "**/*.txt"
