---
stages:
  - build
  - scan

build:
  stage: build
  before_script:
  - apt-get update -qy
  - apt-get install -y maven
  - apt install curl -y
  - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh
      | bash'

  script:
  - mvn clean package


scan:
  script:
  - fossa analyze