---
stages:
  - build
  - scan

build:
  stage: build
  before_script:
  - apt-get update -qy
  - apt-get install -y maven

  script:
    # Add your build commands here
    - mvn clean package
scan:
  stage: scan
  script:
    - fossa analyze