stages:
  - fossa_analysis

fossa_analysis:
  stage: fossa_analysis
  image: fossa/fossa-cli:latest
  script:
    - fossa init            # Initializes FOSSA in the project directory
    - fossa analyze         # Runs the FOSSA analysis