---
stages:
  - build
  - scan

build:
  stage: build
  before_script:
  - apt-get update -qy
  - apt-get install -y maven

  script:
    # Add your build commands here
    - mvn clean package
scan:
  stage: 
  before_script:
  - apt update
  - apt install curl -y
  - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh
      | bash'
  script:
    - fossa analyze