---
variables:
  FOSSA_CLI_VERSION: "latest"
  FOSSA_API_KEY: ${{ secrets.FOSSA_KEY }}

  

stages:
  #- build
  - fossa-scan

#build:
 # stage: build
  #before_script:
  #- apt-get update -qy
  #- apt-get install -y maven
  

  #script:
  #- mvn clean package
fossa-scan:
  stage: fossa-scan
  before_script:
  - apt install curl -y
  - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh
      | bash'
  #- 'curl -H "Authorization: Bearer $FOSSA_API_KEY" https://api.fossa.com/s/analyze.sh | bash'
  - export FOSSA_API_KEY=$FOSSA_KEY
  script:
  - fossa analyze

