---
test:
  image: ubuntu:latest
  script:
  - apt update
  - apt install curl -y
  - - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh
      | bash'
  - export FOSSA_API_KEY=$FOSSA_KEY
  - fossa init
  - [ "fossa analyze --title Java-APP" ]
  - ["echo $CI_BUILDS_DIR $CI_PROJECT_NAME"]